
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Mar 28 15:15:47 CEST 2021
//----------------------------------------------------

package compiler.syntax;

import java_cup.runtime.Symbol;
import java.util.*;
import es.uned.lsi.compiler.lexical.*;
import es.uned.lsi.compiler.code.*;
import es.uned.lsi.compiler.intermediate.*;
import es.uned.lsi.compiler.semantic.*;
import es.uned.lsi.compiler.semantic.symbol.*;
import es.uned.lsi.compiler.semantic.type.*;
import es.uned.lsi.compiler.syntax.*;
import compiler.CompilerContext;
import compiler.lexical.*;
import compiler.syntax.nonTerminal.*;
import compiler.semantic.symbol.*;
import compiler.semantic.type.*;
import compiler.intermediate.*;
import compiler.code.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Sun Mar 28 15:15:47 CEST 2021
  */
public class parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\145\000\002\002\004\000\002\062\002\000\002\002" +
    "\004\000\002\003\003\000\002\004\002\000\002\063\002" +
    "\000\002\024\016\000\002\005\007\000\002\005\003\000" +
    "\002\006\003\000\002\006\003\000\002\006\003\000\002" +
    "\007\004\000\002\007\003\000\002\010\016\000\002\010" +
    "\003\000\002\011\003\000\002\011\003\000\002\012\003" +
    "\000\002\012\003\000\002\012\003\000\002\013\004\000" +
    "\002\013\003\000\002\015\003\000\002\015\003\000\002" +
    "\015\003\000\002\025\004\000\002\025\003\000\002\014" +
    "\007\000\002\014\003\000\002\016\005\000\002\016\003" +
    "\000\002\016\003\000\002\017\004\000\002\017\003\000" +
    "\002\021\003\000\002\021\003\000\002\022\003\000\002" +
    "\022\003\000\002\034\021\000\002\035\023\000\002\036" +
    "\003\000\002\036\003\000\002\020\004\000\002\020\003" +
    "\000\002\023\004\000\002\023\003\000\002\026\005\000" +
    "\002\026\005\000\002\026\003\000\002\026\003\000\002" +
    "\026\003\000\002\026\003\000\002\026\003\000\002\026" +
    "\003\000\002\026\003\000\002\027\005\000\002\027\003" +
    "\000\002\030\005\000\002\030\005\000\002\030\003\000" +
    "\002\031\004\000\002\031\003\000\002\032\005\000\002" +
    "\032\005\000\002\033\006\000\002\041\003\000\002\041" +
    "\003\000\002\042\006\000\002\060\003\000\002\037\003" +
    "\000\002\040\006\000\002\061\004\000\002\045\003\000" +
    "\002\045\003\000\002\045\003\000\002\045\003\000\002" +
    "\045\003\000\002\046\003\000\002\046\003\000\002\046" +
    "\003\000\002\046\003\000\002\046\003\000\002\046\003" +
    "\000\002\047\004\000\002\047\003\000\002\050\004\000" +
    "\002\050\003\000\002\051\013\000\002\052\013\000\002" +
    "\054\005\000\002\054\003\000\002\053\005\000\002\053" +
    "\003\000\002\055\015\000\002\056\015\000\002\043\003" +
    "\000\002\043\003\000\002\043\003\000\002\044\007\000" +
    "\002\057\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\352\000\004\011\000\001\002\000\004\002\354\001" +
    "\002\000\004\011\010\001\002\000\004\002\uffff\001\002" +
    "\000\004\002\ufffe\001\002\000\004\024\011\001\002\000" +
    "\004\052\ufffc\001\002\000\004\052\013\001\002\000\014" +
    "\027\ufffd\041\ufffd\042\ufffd\045\015\050\ufffd\001\002\000" +
    "\012\027\ufffd\041\ufffd\042\031\050\ufffd\001\002\000\014" +
    "\024\020\027\ufffd\041\ufffd\042\ufffd\050\ufffd\001\002\000" +
    "\012\027\ufff4\041\ufff4\042\ufff4\050\ufff4\001\002\000\012" +
    "\027\ufff5\041\ufff5\042\ufff5\050\ufff5\001\002\000\004\055" +
    "\022\001\002\000\012\027\ufff9\041\ufff9\042\ufff9\050\ufff9" +
    "\001\002\000\010\031\026\035\024\047\023\001\002\000" +
    "\004\053\ufff6\001\002\000\004\053\ufff7\001\002\000\004" +
    "\053\027\001\002\000\004\053\ufff8\001\002\000\014\024" +
    "\020\027\ufffd\041\ufffd\042\ufffd\050\ufffd\001\002\000\012" +
    "\027\ufffa\041\ufffa\042\ufffa\050\ufffa\001\002\000\012\024" +
    "\337\027\ufffd\041\ufffd\050\ufffd\001\002\000\010\027\035" +
    "\041\ufffd\050\ufffd\001\002\000\010\027\uffeb\041\uffeb\050" +
    "\uffeb\001\002\000\006\041\130\050\ufffd\001\002\000\030" +
    "\007\051\021\055\024\046\031\053\032\054\033\037\035" +
    "\040\041\ufffd\047\052\050\ufffd\052\ufffd\001\002\000\006" +
    "\041\uffdf\050\uffdf\001\002\000\020\007\051\021\055\024" +
    "\046\031\053\033\037\035\040\047\052\001\002\000\032" +
    "\004\uffce\006\uffce\023\uffce\025\uffce\034\uffce\037\uffce\040" +
    "\uffce\043\uffce\051\uffce\052\uffce\053\uffce\054\uffce\001\002" +
    "\000\006\041\uffe0\050\uffe0\001\002\000\004\052\115\001" +
    "\002\000\022\025\072\034\uffe6\037\073\040\070\043\uffe6" +
    "\051\066\052\uffe6\054\071\001\002\000\032\004\uffc3\006" +
    "\uffc3\023\uffc3\025\uffc3\034\uffc3\037\uffc3\040\uffc3\043\uffc3" +
    "\051\uffc3\052\uffc3\053\uffc3\054\uffc3\001\002\000\032\004" +
    "\uffc5\006\uffc5\023\uffc5\025\uffc5\034\uffc5\037\uffc5\040\uffc5" +
    "\043\uffc5\051\uffc5\052\uffc5\053\uffc5\054\uffc5\001\002\000" +
    "\036\004\uffd0\006\uffd0\021\104\023\uffd0\025\uffd0\033\103" +
    "\034\uffd0\037\uffd0\040\uffd0\043\uffd0\051\uffd0\052\uffd0\053" +
    "\uffd0\054\uffd0\001\002\000\032\004\uffc8\006\uffc8\023\uffc8" +
    "\025\uffc8\034\uffc8\037\uffc8\040\uffc8\043\uffc8\051\uffc8\052" +
    "\uffc8\053\uffc8\054\uffc8\001\002\000\032\004\uffca\006\uffca" +
    "\023\uffca\025\uffca\034\uffca\037\uffca\040\uffca\043\uffca\051" +
    "\uffca\052\uffca\053\uffca\054\uffca\001\002\000\020\007\051" +
    "\021\055\024\046\031\053\033\037\035\040\047\052\001" +
    "\002\000\032\004\uffcb\006\uffcb\023\uffcb\025\uffcb\034\uffcb" +
    "\037\uffcb\040\uffcb\043\uffcb\051\uffcb\052\uffcb\053\uffcb\054" +
    "\uffcb\001\002\000\032\004\uffcd\006\uffcd\023\uffcd\025\uffcd" +
    "\034\uffcd\037\uffcd\040\uffcd\043\uffcd\051\uffcd\052\uffcd\053" +
    "\uffcd\054\uffcd\001\002\000\004\024\101\001\002\000\020" +
    "\007\051\021\055\024\046\031\053\033\037\035\040\047" +
    "\052\001\002\000\032\004\uffcf\006\uffcf\023\uffcf\025\uffcf" +
    "\034\uffcf\037\uffcf\040\uffcf\043\uffcf\051\uffcf\052\uffcf\053" +
    "\uffcf\054\uffcf\001\002\000\010\034\uffe2\043\062\052\uffe2" +
    "\001\002\000\032\004\uffcc\006\uffcc\023\uffcc\025\uffcc\034" +
    "\uffcc\037\uffcc\040\uffcc\043\uffcc\051\uffcc\052\uffcc\053\uffcc" +
    "\054\uffcc\001\002\000\012\034\uffe4\041\uffe4\050\uffe4\052" +
    "\uffe1\001\002\000\026\007\051\021\055\024\046\031\053" +
    "\032\054\033\037\034\ufffd\035\040\047\052\052\ufffd\001" +
    "\002\000\006\034\uffe3\052\uffe3\001\002\000\006\034\uffe1" +
    "\052\uffe1\001\002\000\016\023\067\025\072\037\073\040" +
    "\070\051\066\054\071\001\002\000\020\007\051\021\055" +
    "\024\046\031\053\033\037\035\040\047\052\001\002\000" +
    "\032\004\uffc1\006\uffc1\023\uffc1\025\uffc1\034\uffc1\037\uffc1" +
    "\040\uffc1\043\uffc1\051\uffc1\052\uffc1\053\uffc1\054\uffc1\001" +
    "\002\000\020\007\051\021\055\024\046\031\053\033\037" +
    "\035\040\047\052\001\002\000\020\007\051\021\055\024" +
    "\046\031\053\033\037\035\040\047\052\001\002\000\020" +
    "\007\051\021\055\024\046\031\053\033\037\035\040\047" +
    "\052\001\002\000\020\007\051\021\055\024\046\031\053" +
    "\033\037\035\040\047\052\001\002\000\032\004\uffc6\006" +
    "\uffc6\023\uffc6\025\uffc6\034\uffc6\037\uffc6\040\uffc6\043\uffc6" +
    "\051\uffc6\052\uffc6\053\uffc6\054\uffc6\001\002\000\032\004" +
    "\uffd1\006\uffd1\023\uffd1\025\uffd1\034\uffd1\037\uffd1\040\uffd1" +
    "\043\uffd1\051\uffd1\052\uffd1\053\uffd1\054\uffd1\001\002\000" +
    "\032\004\uffd2\006\uffd2\023\uffd2\025\uffd2\034\uffd2\037\uffd2" +
    "\040\uffd2\043\uffd2\051\uffd2\052\uffd2\053\uffd2\054\uffd2\001" +
    "\002\000\032\004\uffc9\006\uffc9\023\uffc9\025\uffc9\034\uffc9" +
    "\037\uffc9\040\uffc9\043\uffc9\051\uffc9\052\uffc9\053\uffc9\054" +
    "\uffc9\001\002\000\032\004\uffc7\006\uffc7\023\uffc7\025\uffc7" +
    "\034\uffc7\037\uffc7\040\uffc7\043\uffc7\051\uffc7\052\uffc7\053" +
    "\uffc7\054\uffc7\001\002\000\010\034\uffe7\043\uffe7\052\uffe7" +
    "\001\002\000\032\004\uffc4\006\uffc4\023\uffc4\025\uffc4\034" +
    "\uffc4\037\uffc4\040\uffc4\043\uffc4\051\uffc4\052\uffc4\053\uffc4" +
    "\054\uffc4\001\002\000\024\007\051\021\055\024\046\031" +
    "\053\032\054\033\037\034\ufffd\035\040\047\052\001\002" +
    "\000\006\024\110\047\105\001\002\000\006\004\uffef\023" +
    "\uffef\001\002\000\006\004\uffed\023\uffed\001\002\000\004" +
    "\023\111\001\002\000\010\004\uffee\021\104\023\uffee\001" +
    "\002\000\034\004\uffc0\006\uffc0\023\uffc0\025\uffc0\034\uffc0" +
    "\037\uffc0\040\uffc0\043\uffc0\051\uffc0\052\uffc0\053\uffc0\054" +
    "\uffc0\055\uffc0\001\002\000\004\034\114\001\002\000\004" +
    "\034\uffbb\001\002\000\032\004\uffba\006\uffba\023\uffba\025" +
    "\uffba\034\uffba\037\uffba\040\uffba\043\uffba\051\uffba\052\uffba" +
    "\053\uffba\054\uffba\001\002\000\010\012\121\016\120\024" +
    "\116\001\002\000\034\007\uffe8\021\uffe8\024\uffe8\031\uffe8" +
    "\032\uffe8\033\uffe8\034\uffe8\035\uffe8\041\uffe8\047\uffe8\050" +
    "\uffe8\052\uffe8\053\uffe8\001\002\000\034\007\ufffd\021\ufffd" +
    "\024\ufffd\031\ufffd\032\ufffd\033\ufffd\034\ufffd\035\ufffd\041" +
    "\ufffd\047\ufffd\050\ufffd\052\ufffd\053\122\001\002\000\034" +
    "\007\uffea\021\uffea\024\uffea\031\uffea\032\uffea\033\uffea\034" +
    "\uffea\035\uffea\041\uffea\047\uffea\050\uffea\052\uffea\053\uffea" +
    "\001\002\000\034\007\uffe9\021\uffe9\024\uffe9\031\uffe9\032" +
    "\uffe9\033\uffe9\034\uffe9\035\uffe9\041\uffe9\047\uffe9\050\uffe9" +
    "\052\uffe9\053\uffe9\001\002\000\032\007\uffde\021\uffde\024" +
    "\uffde\031\uffde\032\uffde\033\uffde\034\uffde\035\uffde\041\uffde" +
    "\047\uffde\050\uffde\052\uffde\001\002\000\032\007\051\021" +
    "\055\024\046\031\053\032\054\033\037\034\ufffd\035\040" +
    "\041\ufffd\047\052\050\ufffd\052\ufffd\001\002\000\032\007" +
    "\uffdd\021\uffdd\024\uffdd\031\uffdd\032\uffdd\033\uffdd\034\uffdd" +
    "\035\uffdd\041\uffdd\047\uffdd\050\uffdd\052\uffdd\001\002\000" +
    "\010\034\uffe5\041\uffe5\050\uffe5\001\002\000\016\025\072" +
    "\034\127\037\073\040\070\051\066\054\071\001\002\000" +
    "\032\004\uffc2\006\uffc2\023\uffc2\025\uffc2\034\uffc2\037\uffc2" +
    "\040\uffc2\043\uffc2\051\uffc2\052\uffc2\053\uffc2\054\uffc2\001" +
    "\002\000\010\014\221\022\220\050\ufffd\001\002\000\004" +
    "\050\uffd3\001\002\000\004\050\133\001\002\000\014\013" +
    "\ufffd\015\134\017\140\024\141\046\142\001\002\000\004" +
    "\024\206\001\002\000\016\013\uffb8\015\uffb8\017\uffb8\024" +
    "\uffb8\026\uffb8\046\uffb8\001\002\000\004\013\204\001\002" +
    "\000\016\013\ufffd\015\134\017\140\024\141\026\ufffd\046" +
    "\142\001\002\000\020\007\051\021\055\024\046\031\053" +
    "\033\037\035\040\047\052\001\002\000\010\021\104\033" +
    "\103\055\uffbf\001\002\000\004\033\160\001\002\000\004" +
    "\055\154\001\002\000\016\013\uffb5\015\uffb5\017\uffb5\024" +
    "\uffb5\026\uffb5\046\uffb5\001\002\000\016\013\uffb6\015\uffb6" +
    "\017\uffb6\024\uffb6\026\uffb6\046\uffb6\001\002\000\016\013" +
    "\uffb7\015\uffb7\017\uffb7\024\uffb7\026\uffb7\046\uffb7\001\002" +
    "\000\006\013\uffac\026\uffac\001\002\000\004\053\153\001" +
    "\002\000\004\055\uffbe\001\002\000\016\013\uffb4\015\uffb4" +
    "\017\uffb4\024\uffb4\026\uffb4\046\uffb4\001\002\000\020\010" +
    "\uffb9\013\uffb9\015\uffb9\017\uffb9\024\uffb9\026\uffb9\046\uffb9" +
    "\001\002\000\020\007\051\021\055\024\046\031\053\033" +
    "\037\035\040\047\052\001\002\000\004\053\157\001\002" +
    "\000\016\025\072\037\073\040\070\051\066\053\uffbc\054" +
    "\071\001\002\000\020\010\uffbd\013\uffbd\015\uffbd\017\uffbd" +
    "\024\uffbd\026\uffbd\046\uffbd\001\002\000\024\007\051\021" +
    "\055\024\046\030\161\031\053\033\037\034\ufffd\035\040" +
    "\047\052\001\002\000\004\034\uffa1\001\002\000\016\025" +
    "\072\034\uffa0\037\073\040\070\051\066\054\071\001\002" +
    "\000\004\034\165\001\002\000\004\034\uff9f\001\002\000" +
    "\004\053\166\001\002\000\020\010\uff9e\013\uff9e\015\uff9e" +
    "\017\uff9e\024\uff9e\026\uff9e\046\uff9e\001\002\000\016\006" +
    "\170\025\072\037\073\040\070\051\066\054\071\001\002" +
    "\000\004\052\171\001\002\000\016\013\ufffd\015\134\017" +
    "\140\024\141\026\ufffd\046\142\001\002\000\006\013\ufffd" +
    "\026\174\001\002\000\004\013\200\001\002\000\004\052" +
    "\176\001\002\000\004\013\uffa4\001\002\000\014\013\ufffd" +
    "\015\134\017\140\024\141\046\142\001\002\000\004\013" +
    "\uffa5\001\002\000\004\017\201\001\002\000\004\053\202" +
    "\001\002\000\016\013\uffa9\015\uffa9\017\uffa9\024\uffa9\026" +
    "\uffa9\046\uffa9\001\002\000\006\013\uffad\026\uffad\001\002" +
    "\000\004\044\205\001\002\000\004\002\ufffb\001\002\000" +
    "\004\036\207\001\002\000\020\007\051\021\055\024\046" +
    "\031\053\033\037\035\040\047\052\001\002\000\016\004" +
    "\211\025\072\037\073\040\070\051\066\054\071\001\002" +
    "\000\020\007\051\021\055\024\046\031\053\033\037\035" +
    "\040\047\052\001\002\000\016\025\072\037\073\040\070" +
    "\051\066\052\213\054\071\001\002\000\014\013\ufffd\015" +
    "\134\017\140\024\141\046\142\001\002\000\004\013\215" +
    "\001\002\000\004\015\216\001\002\000\004\053\217\001" +
    "\002\000\016\013\uffa3\015\uffa3\017\uffa3\024\uffa3\026\uffa3" +
    "\046\uffa3\001\002\000\004\024\246\001\002\000\004\024" +
    "\230\001\002\000\004\050\uffd4\001\002\000\010\014\uffd8" +
    "\022\uffd8\050\uffd8\001\002\000\010\014\uffd7\022\uffd7\050" +
    "\uffd7\001\002\000\010\014\221\022\220\050\ufffd\001\002" +
    "\000\004\050\uffd5\001\002\000\004\050\uffd6\001\002\000" +
    "\004\033\231\001\002\000\026\007\051\021\055\024\046" +
    "\031\053\032\054\033\037\034\ufffd\035\040\047\052\052" +
    "\ufffd\001\002\000\004\034\233\001\002\000\004\052\234" +
    "\001\002\000\014\027\ufffd\041\ufffd\042\ufffd\045\015\050" +
    "\ufffd\001\002\000\012\027\ufffd\041\ufffd\042\031\050\ufffd" +
    "\001\002\000\010\027\035\041\ufffd\050\ufffd\001\002\000" +
    "\006\041\130\050\ufffd\001\002\000\004\050\241\001\002" +
    "\000\012\015\134\017\140\024\141\046\142\001\002\000" +
    "\014\013\ufffd\015\134\017\140\024\141\046\142\001\002" +
    "\000\004\013\244\001\002\000\004\053\245\001\002\000" +
    "\010\014\uffda\022\uffda\050\uffda\001\002\000\004\033\247" +
    "\001\002\000\026\007\051\021\055\024\046\031\053\032" +
    "\054\033\037\034\ufffd\035\040\047\052\052\ufffd\001\002" +
    "\000\004\034\251\001\002\000\004\052\252\001\002\000" +
    "\010\012\255\016\257\024\254\001\002\000\004\052\260" +
    "\001\002\000\004\052\uffdc\001\002\000\006\052\ufff0\053" +
    "\ufff0\001\002\000\004\052\uffdb\001\002\000\006\052\ufff1" +
    "\053\ufff1\001\002\000\014\027\ufffd\041\ufffd\042\ufffd\045" +
    "\015\050\ufffd\001\002\000\012\027\ufffd\041\ufffd\042\031" +
    "\050\ufffd\001\002\000\010\027\035\041\ufffd\050\ufffd\001" +
    "\002\000\006\041\130\050\ufffd\001\002\000\004\050\265" +
    "\001\002\000\014\010\276\015\266\017\271\024\141\046" +
    "\142\001\002\000\004\024\324\001\002\000\020\010\uffb3" +
    "\013\uffb3\015\uffb3\017\uffb3\024\uffb3\026\uffb3\046\uffb3\001" +
    "\002\000\020\010\uffb1\013\uffb1\015\uffb1\017\uffb1\024\uffb1" +
    "\026\uffb1\046\uffb1\001\002\000\020\007\051\021\055\024" +
    "\046\031\053\033\037\035\040\047\052\001\002\000\020" +
    "\010\uffae\013\uffae\015\uffae\017\uffae\024\uffae\026\uffae\046" +
    "\uffae\001\002\000\020\010\uffb2\013\uffb2\015\uffb2\017\uffb2" +
    "\024\uffb2\026\uffb2\046\uffb2\001\002\000\020\010\uffb0\013" +
    "\uffb0\015\uffb0\017\uffb0\024\uffb0\026\uffb0\046\uffb0\001\002" +
    "\000\016\010\276\013\ufffd\015\266\017\271\024\141\046" +
    "\142\001\002\000\020\007\051\021\055\024\046\031\053" +
    "\033\037\035\040\047\052\001\002\000\020\010\uffaf\013" +
    "\uffaf\015\uffaf\017\uffaf\024\uffaf\026\uffaf\046\uffaf\001\002" +
    "\000\016\025\072\037\073\040\070\051\066\053\301\054" +
    "\071\001\002\000\020\010\uff9d\013\uff9d\015\uff9d\017\uff9d" +
    "\024\uff9d\026\uff9d\046\uff9d\001\002\000\004\013\306\001" +
    "\002\000\020\010\276\013\ufffd\015\266\017\271\024\141" +
    "\026\ufffd\046\142\001\002\000\006\013\uffaa\026\uffaa\001" +
    "\002\000\006\013\uffab\026\uffab\001\002\000\004\053\307" +
    "\001\002\000\010\014\uffd9\022\uffd9\050\uffd9\001\002\000" +
    "\016\006\311\025\072\037\073\040\070\051\066\054\071" +
    "\001\002\000\004\052\312\001\002\000\020\010\276\013" +
    "\ufffd\015\266\017\271\024\141\026\ufffd\046\142\001\002" +
    "\000\006\013\ufffd\026\314\001\002\000\004\052\322\001" +
    "\002\000\004\013\uffa6\001\002\000\004\013\317\001\002" +
    "\000\004\017\320\001\002\000\004\053\321\001\002\000" +
    "\020\010\uffa8\013\uffa8\015\uffa8\017\uffa8\024\uffa8\026\uffa8" +
    "\046\uffa8\001\002\000\016\010\276\013\ufffd\015\266\017" +
    "\271\024\141\046\142\001\002\000\004\013\uffa7\001\002" +
    "\000\004\036\325\001\002\000\020\007\051\021\055\024" +
    "\046\031\053\033\037\035\040\047\052\001\002\000\016" +
    "\004\327\025\072\037\073\040\070\051\066\054\071\001" +
    "\002\000\020\007\051\021\055\024\046\031\053\033\037" +
    "\035\040\047\052\001\002\000\016\025\072\037\073\040" +
    "\070\051\066\052\331\054\071\001\002\000\016\010\276" +
    "\013\ufffd\015\266\017\271\024\141\046\142\001\002\000" +
    "\004\013\333\001\002\000\004\015\334\001\002\000\004" +
    "\053\335\001\002\000\020\010\uffa2\013\uffa2\015\uffa2\017" +
    "\uffa2\024\uffa2\026\uffa2\046\uffa2\001\002\000\010\027\uffec" +
    "\041\uffec\050\uffec\001\002\000\004\055\341\001\002\000" +
    "\010\027\ufff2\041\ufff2\050\ufff2\001\002\000\004\020\342" +
    "\001\002\000\004\021\343\001\002\000\006\024\110\047" +
    "\105\001\002\000\004\004\345\001\002\000\006\024\110" +
    "\047\105\001\002\000\004\023\347\001\002\000\004\005" +
    "\350\001\002\000\006\012\255\016\257\001\002\000\004" +
    "\053\352\001\002\000\012\024\337\027\ufffd\041\ufffd\050" +
    "\ufffd\001\002\000\010\027\ufff3\041\ufff3\050\ufff3\001\002" +
    "\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\352\000\006\002\003\062\004\001\001\000\002\001" +
    "\001\000\006\003\005\024\006\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\063\011\001" +
    "\001\000\002\001\001\000\006\004\015\007\013\001\001" +
    "\000\006\004\032\013\031\001\001\000\006\004\020\005" +
    "\016\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\006\024\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\004\020\005\027\001\001\000\002\001" +
    "\001\000\006\004\337\010\335\001\001\000\006\004\035" +
    "\017\033\001\001\000\002\001\001\000\006\004\130\023" +
    "\131\001\001\000\030\004\060\014\040\016\041\025\056" +
    "\026\042\027\047\030\046\031\044\032\043\033\057\040" +
    "\055\001\001\000\002\001\001\000\020\026\125\027\047" +
    "\030\046\031\044\032\043\033\057\040\055\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\020\026\101" +
    "\027\047\030\046\031\044\032\043\033\057\040\055\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\020\026\064\027\047\030\046\031\044\032\043\033" +
    "\057\040\055\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\026\004\063\016" +
    "\062\025\056\026\042\027\047\030\046\031\044\032\043" +
    "\033\057\040\055\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\020\026\077\027\047\030\046" +
    "\031\044\032\043\033\057\040\055\001\001\000\002\001" +
    "\001\000\020\026\076\027\047\030\046\031\044\032\043" +
    "\033\057\040\055\001\001\000\020\026\075\027\047\030" +
    "\046\031\044\032\043\033\057\040\055\001\001\000\020" +
    "\026\074\027\047\030\046\031\044\032\043\033\057\040" +
    "\055\001\001\000\020\026\073\027\047\030\046\031\044" +
    "\032\043\033\057\040\055\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\030\004" +
    "\063\016\112\025\056\026\042\027\047\030\046\031\044" +
    "\032\043\033\057\037\111\040\055\001\001\000\006\012" +
    "\106\033\105\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\015\116\001\001\000\002\001\001\000\006\004\123\021" +
    "\122\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\030\004\060\014\124\016\041\025\056\026" +
    "\042\027\047\030\046\031\044\032\043\033\057\040\055" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\014\004\225\020\221\034\222" +
    "\035\223\036\224\001\001\000\002\001\001\000\002\001" +
    "\001\000\030\004\146\033\150\040\147\041\142\042\134" +
    "\044\143\045\136\047\135\051\145\055\144\061\151\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\030\004\146\033\150\040\147\041\142\042\134\044" +
    "\143\045\136\047\202\051\145\055\144\061\151\001\001" +
    "\000\020\026\166\027\047\030\046\031\044\032\043\033" +
    "\057\040\055\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\022\026" +
    "\155\027\047\030\046\031\044\032\043\033\057\040\055" +
    "\060\154\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\024\004\163\026\161\027\047\030\046" +
    "\031\044\032\043\033\057\040\055\043\162\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\030\004\146\033\150\040\147" +
    "\041\142\042\134\044\143\045\136\047\171\051\145\055" +
    "\144\061\151\001\001\000\006\004\174\053\172\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\030\004\146\033\150\040\147\041\142\042\134\044\143" +
    "\045\136\047\176\051\145\055\144\061\151\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\020\026\207\027\047\030\046" +
    "\031\044\032\043\033\057\040\055\001\001\000\002\001" +
    "\001\000\020\026\211\027\047\030\046\031\044\032\043" +
    "\033\057\040\055\001\001\000\002\001\001\000\030\004" +
    "\146\033\150\040\147\041\142\042\134\044\143\045\136" +
    "\047\213\051\145\055\144\061\151\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\014\004\225\020\226" +
    "\034\222\035\223\036\224\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\030\004\060\014\231" +
    "\016\041\025\056\026\042\027\047\030\046\031\044\032" +
    "\043\033\057\040\055\001\001\000\002\001\001\000\002" +
    "\001\001\000\006\004\015\007\234\001\001\000\006\004" +
    "\032\013\235\001\001\000\006\004\035\017\236\001\001" +
    "\000\006\004\130\023\237\001\001\000\002\001\001\000" +
    "\024\033\150\040\147\041\142\042\134\044\143\045\241" +
    "\051\145\055\144\061\151\001\001\000\030\004\146\033" +
    "\150\040\147\041\142\042\134\044\143\045\136\047\242" +
    "\051\145\055\144\061\151\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\030" +
    "\004\060\014\247\016\041\025\056\026\042\027\047\030" +
    "\046\031\044\032\043\033\057\040\055\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\011\255\022\252\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\006\004\015\007" +
    "\260\001\001\000\006\004\032\013\261\001\001\000\006" +
    "\004\035\017\262\001\001\000\006\004\130\023\263\001" +
    "\001\000\002\001\001\000\026\033\150\040\147\041\142" +
    "\042\266\044\273\046\274\052\272\056\267\057\271\061" +
    "\276\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\020\026\307\027\047\030\046\031\044\032" +
    "\043\033\057\040\055\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\032\004\303\033\150\040" +
    "\147\041\142\042\266\044\273\046\302\050\301\052\272" +
    "\056\267\057\271\061\276\001\001\000\020\026\277\027" +
    "\047\030\046\031\044\032\043\033\057\040\055\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\032\004\303\033\150\040\147\041\142" +
    "\042\266\044\273\046\302\050\304\052\272\056\267\057" +
    "\271\061\276\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\032\004\303\033\150\040\147\041\142" +
    "\042\266\044\273\046\302\050\312\052\272\056\267\057" +
    "\271\061\276\001\001\000\006\004\314\054\315\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\032" +
    "\004\303\033\150\040\147\041\142\042\266\044\273\046" +
    "\302\050\322\052\272\056\267\057\271\061\276\001\001" +
    "\000\002\001\001\000\002\001\001\000\020\026\325\027" +
    "\047\030\046\031\044\032\043\033\057\040\055\001\001" +
    "\000\002\001\001\000\020\026\327\027\047\030\046\031" +
    "\044\032\043\033\057\040\055\001\001\000\002\001\001" +
    "\000\032\004\303\033\150\040\147\041\142\042\266\044" +
    "\273\046\302\050\331\052\272\056\267\057\271\061\276" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\012\343\033\105\001\001\000\002\001\001\000\006" +
    "\012\345\033\105\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\011\350\001\001\000\002\001\001\000\006" +
    "\004\337\010\352\001\001\000\002\001\001\000\002\001" +
    "\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



	SyntaxErrorManager syntaxErrorManager = CompilerContext.getSyntaxErrorManager();
	
	public void syntax_error(Symbol symbol)
	{ 
	    Token token = (Token) symbol.value;
	    syntaxErrorManager.syntaxError ("Error sintactico", token);	    
	}
		
	public void unrecovered_syntax_error(java_cup.runtime.Symbol symbol)
	{	
	    Token token = (Token) symbol.value;
	    syntaxErrorManager.syntaxFatalError ("Error fatal", token);
	}

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {


	
	SyntaxErrorManager   syntaxErrorManager   = CompilerContext.getSyntaxErrorManager();
	SemanticErrorManager semanticErrorManager = CompilerContext.getSemanticErrorManager ();
	ScopeManagerIF       scopeManager         = CompilerContext.getScopeManager ();
	FinalCodeFactoryIF   finalCodeFactory     = CompilerContext.getFinalCodeFactory ();


  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 100: // sentenciaDevolver ::= FRETURN expresion DSENTENCIAS 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaDevolver",45, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 99: // sentenciaEscribir ::= ESCRIBIR PIZQUIERDO parametroEscribir PDERECHO DSENTENCIAS 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaEscribir",34, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 98: // parametroEscribir ::= epsilon 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametroEscribir",33, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 97: // parametroEscribir ::= expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametroEscribir",33, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 96: // parametroEscribir ::= STRING 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametroEscribir",33, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 95: // sentenciaforFuncion ::= COMIENZOBUCLEPARA IDEN RANGOBUCLEPARA expresion RANGO expresion DELIMFUNC listaSentenciasFuncion FINBLOQUESENTENCIAS COMIENZOBUCLEPARA DSENTENCIAS 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaforFuncion",44, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 94: // sentenciafor ::= COMIENZOBUCLEPARA IDEN RANGOBUCLEPARA expresion RANGO expresion DELIMFUNC listaSentencias FINBLOQUESENTENCIAS COMIENZOBUCLEPARA DSENTENCIAS 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciafor",43, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 93: // rellenoif ::= epsilon 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("rellenoif",41, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 92: // rellenoif ::= ALTERNATIVASI DELIMFUNC listaSentencias 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("rellenoif",41, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 91: // rellenoifFuncion ::= epsilon 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("rellenoifFuncion",42, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 90: // rellenoifFuncion ::= ALTERNATIVASI DELIMFUNC listaSentenciasFuncion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("rellenoifFuncion",42, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 89: // sentenciaifFuncion ::= COMIENZOSI expresion STARTIF DELIMFUNC listaSentenciasFuncion rellenoifFuncion FINBLOQUESENTENCIAS COMIENZOSI DSENTENCIAS 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaifFuncion",40, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 88: // sentenciaif ::= COMIENZOSI expresion STARTIF DELIMFUNC listaSentencias rellenoif FINBLOQUESENTENCIAS COMIENZOSI DSENTENCIAS 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaif",39, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 87: // listaSentenciasFuncion ::= epsilon 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaSentenciasFuncion",38, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 86: // listaSentenciasFuncion ::= sentenciaFuncion listaSentenciasFuncion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaSentenciasFuncion",38, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 85: // listaSentencias ::= epsilon 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaSentencias",37, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 84: // listaSentencias ::= sentencia listaSentencias 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaSentencias",37, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 83: // sentenciaFuncion ::= sentenciaDevolver 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaFuncion",36, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // sentenciaFuncion ::= sentenciallamadafuncion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaFuncion",36, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // sentenciaFuncion ::= sentenciaEscribir 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaFuncion",36, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // sentenciaFuncion ::= sentenciaforFuncion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaFuncion",36, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // sentenciaFuncion ::= sentenciaifFuncion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaFuncion",36, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // sentenciaFuncion ::= sentenciadeasignacion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaFuncion",36, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // sentencia ::= sentenciallamadafuncion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",35, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // sentencia ::= sentenciaEscribir 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",35, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // sentencia ::= sentenciafor 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",35, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // sentencia ::= sentenciaif 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",35, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // sentencia ::= sentenciadeasignacion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",35, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // sentenciallamadafuncion ::= llamadafuncion DSENTENCIAS 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciallamadafuncion",47, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // llamadafuncion ::= IDEN PIZQUIERDO parametrofuncionoproc PDERECHO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("llamadafuncion",30, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // parametrofuncionoproc ::= listavariables 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametrofuncionoproc",29, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // parametroasignacion ::= expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametroasignacion",46, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // sentenciadeasignacion ::= parteizquierdaasignacion ASIGNACION parametroasignacion DSENTENCIAS 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciadeasignacion",32, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // parteizquierdaasignacion ::= miembrovector 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parteizquierdaasignacion",31, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // parteizquierdaasignacion ::= IDEN 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parteizquierdaasignacion",31, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // miembrovector ::= IDEN CIZQUIERDO valorango CDERECHO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("miembrovector",25, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // expresionlvl5 ::= CIZQUIERDO expresion CDERECHO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresionlvl5",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // expresionlvl5 ::= PIZQUIERDO expresion PDERECHO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresionlvl5",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // expresionlvl4 ::= expresionlvl5 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresionlvl4",23, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // expresionlvl4 ::= NOLOGICO expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresionlvl4",23, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // expresionlvl3 ::= expresionlvl4 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresionlvl3",22, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // expresionlvl3 ::= expresion PRODUCTO expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresionlvl3",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // expresionlvl3 ::= expresion YLOGICA expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresionlvl3",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // expresionlvl2 ::= expresionlvl3 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresionlvl2",21, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // expresionlvl2 ::= expresion SUMA expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresionlvl2",21, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // expresion ::= expresionlvl2 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // expresion ::= NUM 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // expresion ::= miembrovector 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // expresion ::= FALSO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // expresion ::= CIERTO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // expresion ::= llamadafuncion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // expresion ::= IDEN 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",20, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // expresion ::= expresion IGUALDAD expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // expresion ::= expresion MENORQUE expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // seccionsubprograma ::= epsilon 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionsubprograma",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // seccionsubprograma ::= COMIENZOSUBPROGRAMAS defsubprograma 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionsubprograma",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // defsubprograma ::= epsilon 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("defsubprograma",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // defsubprograma ::= selectorpof defsubprograma 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("defsubprograma",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // selectorpof ::= funcion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("selectorpof",28, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // selectorpof ::= procedimiento 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("selectorpof",28, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // funcion ::= DECLAREFUNCION IDEN PIZQUIERDO defvariables PDERECHO DELIMFUNC tiporetornofuncion DELIMFUNC seccionconstantes secciontipos seccionvariables seccionsubprograma COMIENZO sentenciaFuncion listaSentenciasFuncion FINBLOQUESENTENCIAS DSENTENCIAS 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-15)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-15)).right;
		Token id = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-15)).value;
		
	ScopeIF scope = scopeManager.getCurrentScope();
	SymbolTableIF symbolTable = scope.getSymbolTable();
	TypeTableIF typeTable = scope.getTypeTable();
	
	if (typeTable.containsType(id.getLexema()) || symbolTable.containsSymbol(id.getLexema())) {
		 
		System.out.println("\nEstoy en IF\n");
		
		semanticErrorManager.semanticFatalError("Error al declarar la funcion "+id.getLexema()+", ya ha sido declarada");
		
    } else {
    	System.out.println("\nEstoy en ELSE\n");
    	
    	// Insertar tabla tipos y tabla simbolos para la función		
		ScopeIF scopeP = scopeManager.getCurrentScope();
		SymbolTableIF symbolTableP = scopeP.getSymbolTable();
		TypeTableIF typeTableP = scopeP.getTypeTable();
		
		// Crear Tipo y Simbolo de la Función
		TypeFunction tipoFuncion = new TypeFunction(scope, id.getLexema());		
		typeTableP.addType(id.getLexema(), tipoFuncion);
		SymbolFunction simboloFuncion = new SymbolFunction(scope, id.getLexema(), typeTableP.getType(id.getLexema()));
        
        symbolTableP.addSymbol(id.getLexema(),simboloFuncion);
		syntaxErrorManager.syntaxInfo("Funcion en las tablas: "+id.getLexema());
		
		//Crear ambito para la función
		ScopeIF scopeF = scopeManager.openScope (id.getLexema());
		SymbolTableIF symbolTableF = scopeF.getSymbolTable();
		TypeTableIF typeTableF = scopeF.getTypeTable();
	
				
	
		//Para comprobar el nombre del ámbito...
		System.out.println("El nombre del nuevo ámbito es :" + scopeF.getName());
		
		//Para comprobar el nivel del ámbito...
		System.out.println("El nivel del nuevo ámbito es :" + scopeF.getLevel());
				
		System.out.println("Cerrando el ámbito :" + scopeP.getName());
		scopeManager.closeScope();	
    }

              CUP$parser$result = parser.getSymbolFactory().newSymbol("funcion",27, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-16)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // procedimiento ::= COMIENZOPROCEDIMIENTO IDEN PIZQUIERDO defvariables PDERECHO DELIMFUNC seccionconstantes secciontipos seccionvariables seccionsubprograma COMIENZO sentencia listaSentencias FINBLOQUESENTENCIAS DSENTENCIAS 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-13)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-13)).right;
		Token id = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-13)).value;
		
	ScopeIF scope = scopeManager.getCurrentScope();
	SymbolTableIF symbolTable = scope.getSymbolTable();
	TypeTableIF typeTable = scope.getTypeTable();
	
	if (typeTable.containsType(id.getLexema()) || symbolTable.containsSymbol(id.getLexema())) {
		 
		System.out.println("\nEstoy en IF\n");
		
		semanticErrorManager.semanticFatalError("Error al declarar la funcion "+id.getLexema()+", ya ha sido declarada");
		
    } else {
    	System.out.println("\nEstoy en ELSE\n");
    	
    	// Insertar tabla tipos y tabla simbolos para la funciï¿½n		
		ScopeIF scopeP = scopeManager.getCurrentScope();
		SymbolTableIF symbolTableP = scopeP.getSymbolTable();
		TypeTableIF typeTableP = scopeP.getTypeTable();
		
		// Crear Tipo y Simbolo de la Función
		TypeProcedure tipoProcedure = new TypeProcedure(scope, id.getLexema());		
		typeTableP.addType(id.getLexema(), tipoProcedure);
		SymbolProcedure simboloProcedimiento = new SymbolProcedure(scope, id.getLexema(), typeTableP.getType(id.getLexema()));
        
        symbolTableP.addSymbol(id.getLexema(),simboloProcedimiento);
		syntaxErrorManager.syntaxInfo("Procedimiento en las tablas: "+id.getLexema());
		
		//Crear ambito para la función
		ScopeIF scopeF = scopeManager.openScope (id.getLexema());
		SymbolTableIF symbolTableF = scopeF.getSymbolTable();
		TypeTableIF typeTableF = scopeF.getTypeTable();
	
				
	
		//Para comprobar el nombre del ámbito...
		System.out.println("El nombre del nuevo ámbito es :" + scopeF.getName());
		
		//Para comprobar el nivel del ámbito...
		System.out.println("El nivel del nuevo ámbito es :" + scopeF.getLevel());
				
		System.out.println("Cerrando el ámbito :" + scopeP.getName());
		scopeManager.closeScope();	
    }
	
	

              CUP$parser$result = parser.getSymbolFactory().newSymbol("procedimiento",26, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-14)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // tiporetornofuncion ::= tipovector 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tiporetornofuncion",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // tiporetornofuncion ::= IDEN 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tiporetornofuncion",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // puntoycomaopcional ::= epsilon 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("puntoycomaopcional",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // puntoycomaopcional ::= DSENTENCIAS 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("puntoycomaopcional",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // seccionvariables ::= epsilon 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionvariables",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // seccionvariables ::= DECLVARIABLES defvariables 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionvariables",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // listavariables ::= epsilon 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listavariables",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // listavariables ::= selectorvalororeferencia 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listavariables",12, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // listavariables ::= selectorvalororeferencia DIDENTIFICADORES listavariables 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listavariables",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // defvariables ::= epsilon 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("defvariables",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // defvariables ::= listavariables DELIMFUNC tipovariable puntoycomaopcional defvariables 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("defvariables",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // selectorvalororeferencia ::= expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("selectorvalororeferencia",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // selectorvalororeferencia ::= PARAMETROVALOR IDEN 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("selectorvalororeferencia",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // tipovariable ::= IDEN 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipovariable",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // tipovariable ::= ENTERO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipovariable",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // tipovariable ::= BOOLEANO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipovariable",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // secciontipos ::= epsilon 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("secciontipos",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // secciontipos ::= COMIENZODECLTIPOS deftipos 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("secciontipos",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // valorango ::= miembrovector 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("valorango",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // valorango ::= IDEN 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("valorango",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // valorango ::= NUM 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("valorango",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // tipovector ::= ENTERO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipovector",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // tipovector ::= BOOLEANO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipovector",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // deftipos ::= epsilon 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("deftipos",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // deftipos ::= IDEN ASIGNACION DECLVECTOR CIZQUIERDO valorango RANGO valorango CDERECHO ASIGNACIONVECTOR tipovector DSENTENCIAS deftipos 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("deftipos",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-11)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // seccionconstantes ::= epsilon 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionconstantes",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // seccionconstantes ::= BCONSTANTES defconstantes 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionconstantes",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // valorconstante ::= NUM 
            {
              Constante RESULT =null;
		
	Constante c = new Constante();
	c.setTipo("ENTERO");
	RESULT = c;							

              CUP$parser$result = parser.getSymbolFactory().newSymbol("valorconstante",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // valorconstante ::= CIERTO 
            {
              Constante RESULT =null;
		
	Constante c = new Constante();
	c.setTipo("LOGICO");
	RESULT = c;							

              CUP$parser$result = parser.getSymbolFactory().newSymbol("valorconstante",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // valorconstante ::= FALSO 
            {
              Constante RESULT =null;
		
	Constante c = new Constante();
	c.setTipo("LOGICO");
	RESULT = c;							

              CUP$parser$result = parser.getSymbolFactory().newSymbol("valorconstante",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // defconstantes ::= epsilon 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("defconstantes",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // defconstantes ::= IDEN ASIGNACION valorconstante DSENTENCIAS defconstantes 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		Token id = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int valorleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int valorright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Constante valor = (Constante)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		
	//Recuperamos el ámbito dinde nos encontramos y obtenemos la tabla de sï¿½mbolos
	ScopeIF scope = scopeManager.getCurrentScope();
	SymbolTableIF tablaSimbolos = scope.getSymbolTable();
	
	//Comprobamos que la constante no este ya contenida en la tabla de sï¿½mbolos
	if(tablaSimbolos.containsSymbol(id.getLexema())){
		semanticErrorManager.semanticFatalError("Constante " +id.getLexema() + " en linea " + id.getLine() + " ya declarada");
	} else {
		System.out.println("Constante " +id.getLexema() + " en linea " + id.getLine() + " aún No declarada");	
		
		//Introducimos en la tabla de símbolos la constante con su ámbito, nombre, tipo y valor
		TypeTableIF tablaTipos = scope.getTypeTable();
		TypeIF tipo = scopeManager.searchType(valor.getTipo());
		SymbolConstant simboloConstante = new SymbolConstant(scope, id.getLexema(), tipo);
		tablaSimbolos.addSymbol(simboloConstante);
	}

              CUP$parser$result = parser.getSymbolFactory().newSymbol("defconstantes",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // defprincipal ::= COMIENZOPROGRAMA IDEN NT$1 DELIMFUNC seccionconstantes secciontipos seccionvariables seccionsubprograma COMIENZO listaSentencias FINBLOQUESENTENCIAS FINPROGRAMA 
            {
              Object RESULT =null;
              // propagate RESULT from NT$1
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-9)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-10)).right;
		Token id = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-10)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("defprincipal",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-11)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // NT$1 ::= 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Token id = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;

	//Creamos el ámbito global con el nombre del programa principal
	String nombre = id.getLexema();
	scopeManager.openScope(nombre);
	ScopeIF scope = scopeManager.getCurrentScope();
	
	//Para comprobar el nombre del ámbito...
	System.out.println("El nombre del nuevo ámbito es :" + scope.getName());
	
	//Para comprobar el nivel del ámbito...
	System.out.println("El nivel del nuevo ámbito es :" + scope.getLevel());
	
	//Obtenemos del ámbito creado la Tabla de Tipos
	TypeTableIF typeTable = scope.getTypeTable();
	
	//Introducciï¿½n del Tipo Simple Entero o Integer y Lï¿½gico o Booleano
	TypeSimple tsEntero = new TypeSimple(scope, "ENTERO");
	typeTable.addType("ENTERO", tsEntero);
	TypeSimple tsLogico = new TypeSimple(scope, "LOGICO");
	typeTable.addType("LOGICO", tsLogico);

              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$1",49, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // epsilon ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("epsilon",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // axiom ::= defprincipal 
            {
              Axiom RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("axiom",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // program ::= NT$0 axiom 
            {
              Object RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int axleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int axright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Axiom ax = (Axiom)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
  		// No modificar esta estructura, aunque se pueden aï¿½adir mï¿½s acciones semï¿½nticas
  		
  		//List intermediateCode = ax.getIntermediateCode ();
  		//finalCodeFactory.create (intermediateCode);

  		// En caso de no comentarse las dos sentencias anteriores puede generar una excepcion
  		// en las llamadas a cupTest si el compilador no estÃ¡ completo. Esto es debido a que 
  		// aÃºn no se tendrÃ¡ implementada la generaciÃ³n de cÃ³digo intermedio ni final.
  		// Para la entrega final deberÃ¡n descomentarse y usarse.
  		
  		syntaxErrorManager.syntaxInfo ("Parsing process ended.");
   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // NT$0 ::= 
            {
              Object RESULT =null;
 
        syntaxErrorManager.syntaxInfo ("Starting parsing..."); 
   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$0",48, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

